apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  progressDeadlineSeconds: {{ .Values.container.progressDeadlineSeconds }}
  strategy:
    {{ .Values.strategy.type }}:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
    type: {{ .Values.strategy.type }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          resources:
            limits:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
